version: '3'
services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft
    ports:
      - "8282:25565"
      - "28016:28016"
    environment:
      EULA: "TRUE"
      TYPE: "forge"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "123secret*"
      RCON_PORT: 28016
    volumes:
      - "../minecraft/data/config:/data/config"
      - "../minecraft/data/mods:/data/mods"
      - "../minecraft/data/world:/data/world"
      - "../minecraft/modpacks:/modpacks"
  rcon:
    image: itzg/rcon
    container_name: rcon
    ports:
      - "4326:4326"
      - "4327:4327"
    volumes:
      - "../rcon/db:/opt/rcon-web-admin/db"

