version: '3'
services:
  minecraft:
    image: itzg/minecraft-server
    ports:
      - "8282:25565"
      - "28016:28016"
    environment:
      EULA: "TRUE"
      TYPE: "forge"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "testing"
      RCON_PORT: 28016
    volumes:
      - "../data:/data"
      - "../modpacks:/modpacks"
  rcon:
    image: itzg/rcon
    ports:
      - "4326:4326"
      - "4327:4327"
    volumes:
      - "../rcon-db:/opt/rcon-web-admin/db"

